food = input("What is your favorite food? ")
plant = input("What is your favorite plant? ")
cooking = input("What is your favorite method of cooking? ")
burned = input("What is a word to describe burned food? ")
item = input("What is your favorite household item? ")
print()
print("MENU")
print(cooking, food, "with", burned, plant, "on a bed of", item)
